name: Deploy to server

on:
  push:
    branches:
      - 'master'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Package
        run: mvn -B clean compile package -DskipTests

      - name: Copy file via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          PORT: ${{ secrets.SERVER_PORT }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "./target/app.jar"
          target: "/var/chat/"

      - name: Run application as service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/palantir_telegram
            cp /var/chat/target/app.jar /var/chat/app.jar
            rm -rf /var/chat/target
            systemctl stop chat.service
            systemctl start chat.service